version: 2

models:
  - name: ohlc_enriched
    description: "Enriched Solana OHLC 4-hour data with calculated candle attributes"
    columns:
      - name: ts
        description: "Timestamp of the 4-hour interval"
        tests:
          - not_null
      - name: open
        description: "Opening price"
      - name: high
        description: "Highest price"
      - name: low
        description: "Lowest price"
      - name: close
        description: "Closing price"
      - name: mid_price
        description: "Midpoint between high and low"
      - name: candle_body_size
        description: "Absolute size of candle body"
      - name: upper_wick
        description: "Distance from top of body to high"
      - name: lower_wick
        description: "Distance from low to bottom of body"
      - name: candle_type
        description: "Candle type: bullish, bearish, or doji"
      - name: percent_change
        description: "Percent change from open to close"
      - name: volatility
        description: "Volatility: (high - low) / open"
      - name: is_green
        description: "TRUE if bullish candle, FALSE otherwise"

  - name: ohlc_daily
    description: "Aggregated daily Solana OHLC data"
    columns:
      - name: day
        description: "Date of aggregation"
        #add a dbt_test function to make sure the attribute is not null and unique
        tests:
          - not_null
          - unique
      - name: open
        description: "First open price of the day"
      - name: high
        description: "Highest price of the day"
      - name: low
        description: "Lowest price of the day"
      - name: close
        description: "Last close price of the day"
